### Project ###
projectGroup=com.hypeline

### Spring ###
springBootVersion=3.5.16
springDependencyManagementVersion=1.1.7
springCloudDependenciesVersion=2025.0.3

### Libraries ###
springDocOpenApiVersion=2.9.0
instancioJUnitVersion=6.0.0
slackAppenderVersion=1.6.1

### Gradle ###
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=768m
