### Project ###
projectGroup=com.hypeline

### Spring ###
springBootVersion=3.4.4
springDependencyManagementVersion=1.1.7
springCloudDependenciesVersion=2024.0.1

### Libraries ###
testcontainersVersion=2.0.2
springDocOpenApiVersion=2.7.0
mockitoVersion=5.14.0
instancioJUnitVersion=5.0.2
slackAppenderVersion=1.6.1

### Gradle ###
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=768m
